#!/usr/bin/env bash
# a new ubuntu machine by installing
# Nginx be listening on port 80
# Serve a page that return a Hello World string
#

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup  index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restart nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
