#!/usr/bin/env bash
# get info about school life file
FILE="school"
if [ -e $FILE ]
then
	echo "$FILE file exists"
	if [ -s $FILE ]
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi

	if [ -f $FILE ]
	then
		echo "$FILE is a reqular file"
	fi
else
	echo "$FILE file does not exisit"
fi
